CREATE TABLE TASKS (
TASK_ID INT IDENTITY(1,1) PRIMARY KEY,
TASK_NAME NVARCHAR(100) NOT NULL,
ASSIGNEE NVARCHAR(50) NOT NULL,
DUE_DATE DATE NOT NULL,
STATUS NVARCHAR(20) NOT NULL CHECK (STATUS IN (N'未着手', N'進行中', N'完了')),
CREATE_DATETIME DATETIME NOT NULL DEFAULT GETDATE(),
UPDATE_DATETIME DATETIME NOT NULL DEFAULT GETDATE()
);

INSERT INTO TASKS (TASK_NAME, ASSIGNEE, DUE_DATE, STATUS) VALUES
(N'C#最終課題の要件定義書確認', N'内田', '2026-06-15', N'進行中'),
(N'評価シートのフォーマット作成', N'王', '2026-06-18', N'未着手'),
(N'インフラ環境の仮想マシン構築', N'内田', '2026-06-10', N'完了'),
(N'SQL ServerローカルDB疎通確認', N'王', '2026-06-12', N'進行中');